### ISSUE TITLE
Unity integration

### ISSUE THREAD

**Issue by ENikS** [roblevine/UnityLog4NetExtension#10]
Hey Rob,

Would you be interested to contribute your extension to Unity project? I'd like to add something like this to Unity and it might as well be your implementation. It could be released as part of Unity library...
I really could use some help on the team.

Perhaps this extension could add support for other logger engines as well...

**Comment by roblevine** [comment]
Hi @ENikS,

Yes - I'd be more than happy to contribute this to the project. The truth is, I don't use Unity so much any more, so I'm a little out-of-date (as you can see from the difficulty I'm having getting the extension to work reliably with v5).

How would you like to proceed with bringing the extension into Unity?

Thanks,

**Comment by ENikS** [comment]
You could just transfer ownership to unitycontainer organization. I'll add you as a team member so you maintain write access to the repo.
