### ISSUE TITLE
Is there a way to call resolve<ILog> ? 

### ISSUE THREAD

**Issue by Ali-Nass** [roblevine/UnityLog4NetExtension#12]
I'm trying to get a logger to my class, passing ILog to my constructor is working perfectly like 

```
public class test
{
    private ILog logger;
    public test (ILog logger)
    {
        this.logger =logger;
    }
}
```

But I have a class with no constructor and I can't pass the logger to it. Is there a way to resolve such an issue? I tried the following but it failed miserably 

```
public ILog GetLogger()
{
    return DIContainer.Container.Resolve<ILog>();
}
```

**Comment by roblevine** [comment]
Hi,

No - this isn't currently supported. 
Out of interest, what would you expect the type to be of the returned logger?

i.e. what would be the type T below, in the equivalent GetLogger call:

var logger = LogManager.GetLogger(typeof(T));

Thanks,

**Comment by roblevine** [comment]
Ignore my previous reply. I've had a think about this.

No - it isn't supported; it doesn't fit with what the extension is for. What you require can be done directly using the static LogManager factory provided by log4net:

`var logger = LogManager.GetLogger(typeof(TypeForLogger));`

If you'd rather not have a static factory, then just wrap this into your own factory class, register it with the DI container to return this instead:

Factory class:
```
public class LogFactory
{
    public ILog GetLogger(Type type)
    {
         return LogManager.GetLogger(type);
    }
}

```
Usage:
```
public ILog GetLogger(Type t)
{
    return DIContainer.Container.Resolve<LogFactory>().GetLogger(t);
}
```
