### ISSUE TITLE
Does it create a singleon Ilog or a transient?

### ISSUE THREAD

**Issue by justinhomes** [roblevine/UnityLog4NetExtension#6]
Does it create a singleton Ilog or a transient? or can i control that behavior

**Comment by roblevine** [comment]
Apologies for not getting back to you sooner - I somehow missed this issue being raised.

Internally, this uses the log4net `LogManager.GetLogger`, so it has the same behaviour as that.

I believe that this is a singleton for each logger type.

Thanks,

Rob
