### ISSUE TITLE
Extension not working with version bigger than 2.0.3

### ISSUE THREAD

**Issue by bendichthaenni79** [roblevine/UnityLog4NetExtension#7]
I cannot use the extension with a new version in my case 2.0.8.

**Comment by roblevine** [comment]
Hi,

There are two versions of this extension:
v1.x.x - current version v1.2.1 - targets Unity v2 & 3
v2.x.x - current version v2.0.1 - targets Unity v4

Can you confirm which version of the extension you are using, and which version of Unity you are targetting? Also, please explain what you mean by "not working" - in what way is it not working?

Thanks,

Rob

**Comment by bendichthaenni79** [comment]
Hi rob thank you for your reply. And sorry for my sparse explanation. I wanted to use log4net 2.0.8 and the log4net extension. And Unity v4.0.1 It seems that i had to downgrade log4net to version 2.0.3. to make it work. 

I use this constellation in a plugin dll loaded dynamically by an arcgispro application. And the plugin uses log4net and unity. It turned out that the bindingredirect in the dlls config had no effect. I had to introduce the redirect in the arcgispro application config file. Or downgrade the version of the log4net dll to 2.0.3. Is there a way to define the redirect in the assemblies / plugin / dlls config file?

This was the exception i got without the redirect in the main application:
Microsoft.Practices.Unity.ResolutionFailedException was unhandled by user code
  HResult=-2146233088
  Message=Resolution of the dependency failed, type = "myTest.Config.StartupConfiguration", name = "(none)".
Exception occurred while: while resolving.
Exception is: FileNotFoundException - Die Datei oder Assembly "log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving myTest.Config.StartupConfiguration,(none)

  Source=Microsoft.Practices.Unity
  TypeRequested=StartupConfiguration
  StackTrace:
       bei Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
       bei Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
       bei Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)

**Comment by roblevine** [comment]
I can't recreate this problem - it works for me with log4net v2.0.8.
I'd suggest creating a single project solution with log4net v2.0.8, Unity and this extension to test it out - you should see this working. If so, then this might possibly be related to something such as other binding redirects. Do you see any other compile warnings or errors other than what you've highlighted?

**Comment by bendichthaenni79** [comment]
Hi Rob, 
It is binding redirect related. 
We develop a plugin that uses the log4net extension but the main application that loads the plugin is a 3rd Party Product that has only eventlog logging no log4net. So adding the redirect to the main application solves my problem. I have to alter the main applications config to contain the redirect file after the installation.
